// <auto-generated />
using System;
using BlazorSyncfusion.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorSyncfusion.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230519132845_Department")]
    partial class Department
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorSyncfusion.Shared.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longtitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AspIT Nordjylland"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AspIT Østjylland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AspIT Trekanten"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AspIN"
                        });
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmployee")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6336),
                            DepartmentId = 1,
                            FirstName = "Kenneth",
                            IsEmployee = true,
                            LastName = "Hougaard Soerensen",
                            Mail = "keso@aspit.dk",
                            NickName = "KESO",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6383),
                            DepartmentId = 1,
                            FirstName = "Mads",
                            IsEmployee = true,
                            LastName = "Mikkel Rasmussen",
                            Mail = "mara@aspit.dk",
                            NickName = "MARA",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6386),
                            DepartmentId = 4,
                            FirstName = "Dea",
                            IsEmployee = true,
                            LastName = "Gram",
                            Mail = "degr@aspin.dk",
                            NickName = "DEGR",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6388),
                            DepartmentId = 4,
                            FirstName = "Jan",
                            IsEmployee = true,
                            LastName = "Lindgaard Pedersen",
                            Mail = "jape@aspin.dk",
                            NickName = "JAPE",
                            Title = "Lærer"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6391),
                            DepartmentId = 1,
                            FirstName = "Jesper",
                            IsEmployee = true,
                            LastName = "Lade Mathiesen",
                            Mail = "jema@aspit.dk",
                            NickName = "JEMA",
                            Phone = "+45 72 16 28 56",
                            Title = "Specialpædagogisk vejleder"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6394),
                            DepartmentId = 1,
                            FirstName = "Henrik",
                            IsEmployee = true,
                            LastName = "Stephansen",
                            Mail = "hens@aspit.dk",
                            NickName = "HENS",
                            Phone = "+45 72 16 26 85",
                            Title = "Praktik- og jobvejleder"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1994, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateHired = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6396),
                            DepartmentId = 1,
                            FirstName = "Ole",
                            IsEmployee = true,
                            LastName = "Bay Jensen",
                            Mail = "oje@aspit.dk",
                            NickName = "OJE",
                            Phone = "+45 72 16 27 99",
                            Title = "Uddannelseschef"
                        });
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6526),
                            EmployeeId = 5,
                            Text = "ADHD child and very annoying."
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2023, 5, 19, 15, 28, 45, 374, DateTimeKind.Local).AddTicks(6530),
                            EmployeeId = 1,
                            Text = "funny."
                        });
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Entities.Employee", b =>
                {
                    b.HasOne("BlazorSyncfusion.Shared.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Entities.Note", b =>
                {
                    b.HasOne("BlazorSyncfusion.Shared.Entities.Employee", "Employee")
                        .WithMany("Notes")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BlazorSyncfusion.Shared.Entities.Employee", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
